### ISSUE TITLE
Restore Button

### ISSUE THREAD

**Issue by benkaiser** [originalmind/newtab#1]
From the README

> If possible, don't override the tab when the Restore button is present. (post crash)

Can you please update this issue if you get anywhere with this?

Just a few ideas (I have written extensions myself but not regarding this functionality),
- Could you keep a counter of how many tabs have been opened, and if this is the first time in the session maybe have a delay of 5-10 seconds before redirecting so the user has a chance to press restore?
- Does the browser have some kind of uptime value that can tell you it has just been opened?

I use Chrome on Linux and I only tend to only close chrome when I reboot, and this causes chrome to show the restore button every time I open it which makes it incredibly annoying if I miss clicking the button.

**Comment by originalmind** [comment]
Hi Ben,

Thanks for your interest in this extension.
I also find this annoying when there is a genuine crash. 

The Chrome extension API doesn't seem to expose runtime, however the tab count idea could work.
I've been testing a couple of avenues, so I'll update here if I get anywhere.

Cheers,
Joe

**Comment by benkaiser** [comment]
Thanks @originalmind I really appreciate you having a look into this :+1:

**Comment by originalmind** [comment]
Hi Ben,

I've released a new version on the Chrome Web Store which should take care of this.
Let me know if it works for your use case.

**Comment by benkaiser** [comment]
This worked btw. Love your work man
