### ISSUE TITLE
Omnibox not cleared

### ISSUE THREAD

**Issue by wilsonwc** [originalmind/newtab#2]
On windows the omnibox is selected after navigating to the apps page, allowing you to do Ctrl+T and start typing the address of the page you want to go to right away.  This doesnt work in OSX, the cursor is put at the end of the address so you start typing after the chrome://apps.  Would be nice if the location could be cleared or selected in OSX so that upon typing it would be cleared.

**Comment by joe-niland** [comment]
Hi Ross,
Thanks for reporting this.
I had reported this as a bug in Chrome (https://code.google.com/p/chromium/issues/detail?id=471635) and it's apparently been fixed. I'm not sure which Chrome release it'll appear in though.

As an aside, the Chrome extension API doesn't allow any control on the omnibox selection so we have to rely on Chrome's behaviour.

Cheers!
Joe

**Comment by wilsonwc** [comment]
Great! Looks like it is in Chrome 45 which is the current dev build (44 is
beta and 43 is stable).  I have tested it and it's working like it used to!

Ross Wilson
Wilson Web Consulting LLC

**Comment by originalmind** [comment]
Thanks for the feedback, Ross. I am also waiting for this change to make it to beta on Mac!
