### ISSUE TITLE
Link back from webstore

### ISSUE THREAD

**Issue by benkaiser** [originalmind/newtab#3]
Can you link back from the chrome web store app description to this item? I knew I had yours installed, but didn't know what the repo was. It would be useful for users to know where they can go to contribute.

**Comment by originalmind** [comment]
Hi Ben,
Thanks for getting in touch.
I do have a link in the Overview under Feedback, although it's quite a way down.
Is that what you meant?
Cheers
Joe

**Comment by benkaiser** [comment]
Ah yes, apologies, its there. All good :)
